### PR TITLE
This works, but it isn't perfect

### PR DESCRIPTION
**Pull request by pitaj**
I'm kinda disappointed that these header errors keep coming up.

But hey, you did ask for it.

### CODE REVIEW

**Comment by julianlam** [comment]
@pitaj Can you re-submit this as just your own changes? I've merged #17 in on its own, and I don't quite know what you fixed in this PR :smile:

**Comment by pitaj** [comment]
It fixes the problem where you can't go back the the homepage without going to `/home`

**Comment by pitaj** [comment]
But I guess I'll redo it

**Comment by julianlam** [comment]
Thanks @pitaj :D

**Comment by pitaj** [comment]
New PR #19

**Pull request closed without merging**
