### PR TITLE
fix #24

### LINKED ISSUE #24: Even with no sidebar content on latest nodebb; I get col-md-9
I upgraded to the latest nodebb and locally testing shows that I no longer have a fullscreen wide custom homepage and instead it's defaulting to the col-md-9 class.

I have no sidebar content registered for that page; is there something that I can change? Anything required for details?

Thanks!

### PR DESCRIPTION
**Pull request by phit**

### CODE REVIEW

**Comment by julianlam** [comment]
@psychobunny

**Comment by pitaj** [comment]
@phit Fix the merge conflicts please

**Comment by phit** [comment]
should be good to go

**Comment by psychobunny** [comment]
thanks!

**Pull request merged**
